// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxosPYKBBvnMEsEpMUpc4RwZrGkU5LkP0',
    appId: '1:896846880323:web:8db478d5a91ca191adfef6',
    messagingSenderId: '896846880323',
    projectId: 'todo-9fcb4',
    authDomain: 'todo-9fcb4.firebaseapp.com',
    storageBucket: 'todo-9fcb4.firebasestorage.app',
    measurementId: 'G-CP7GXPV93M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCa8zCFdDKJtRyTsDUFH_S6imEy1by_tY',
    appId: '1:896846880323:android:a875513882f368c1adfef6',
    messagingSenderId: '896846880323',
    projectId: 'todo-9fcb4',
    storageBucket: 'todo-9fcb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh73e63no8RvL2PMXm_edRpNTgWUGFbGU',
    appId: '1:896846880323:ios:3c064bc2dda1c187adfef6',
    messagingSenderId: '896846880323',
    projectId: 'todo-9fcb4',
    storageBucket: 'todo-9fcb4.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh73e63no8RvL2PMXm_edRpNTgWUGFbGU',
    appId: '1:896846880323:ios:3c064bc2dda1c187adfef6',
    messagingSenderId: '896846880323',
    projectId: 'todo-9fcb4',
    storageBucket: 'todo-9fcb4.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxosPYKBBvnMEsEpMUpc4RwZrGkU5LkP0',
    appId: '1:896846880323:web:9739e81c70c87d3badfef6',
    messagingSenderId: '896846880323',
    projectId: 'todo-9fcb4',
    authDomain: 'todo-9fcb4.firebaseapp.com',
    storageBucket: 'todo-9fcb4.firebasestorage.app',
    measurementId: 'G-R1SHZD42D7',
  );
}
